#pragma once

#define MONOMYTH_PACKET_AUTH_STATS 0
#define MONOMYTH_LABELS 0
#define MONOMYTH_D3D_OVERLAY 0
#define MONOMYTH_MULTICLASS_DISPLAY 0
#define MONOMYTH_DEBUG_HOOKS 0
#define MONOMYTH_ENABLE_MULTIPET_WINDOW 1
